try {
	${1:// code...}
} catch (${2:Exception} $e) {
	${3:echo 'Caught exception: ',  $e->getMessage(), "\n"};
}

